# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message.proto',
  package='message',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\rmessage.proto\x12\x07message\"\xe1\x03\n\x07Message\x12*\n\x04type\x18\x01 \x01(\x0e\x32\x1c.message.Message.MessageType\x12)\n\x07request\x18\x02 \x01(\x0b\x32\x18.message.Message.Request\x12+\n\x08response\x18\x03 \x01(\x0b\x32\x19.message.Message.Response\x1az\n\x05State\x12\x10\n\x08\x62\x61llVelX\x18\x01 \x01(\x01\x12\x10\n\x08\x62\x61llVelY\x18\x02 \x01(\x01\x12\x12\n\nplayerVelX\x18\x03 \x01(\x01\x12\x12\n\nplayerVelY\x18\x04 \x01(\x01\x12\x10\n\x08\x64istance\x18\x05 \x01(\x01\x12\x13\n\x0b\x61ngleToBall\x18\x06 \x01(\x01\x1a\x1c\n\x06\x43onfig\x12\x12\n\nisTraining\x18\x01 \x01(\x08\x1ai\n\x07Request\x12%\n\x05state\x18\x01 \x01(\x0b\x32\x16.message.Message.State\x12\x0e\n\x06target\x18\x02 \x01(\x01\x12\'\n\x06\x63onfig\x18\x03 \x01(\x0b\x32\x17.message.Message.Config\x1a\x19\n\x08Response\x12\r\n\x05value\x18\x01 \x01(\x01\"2\n\x0bMessageType\x12\x0c\n\x08GETVALUE\x10\x01\x12\t\n\x05LEARN\x10\x02\x12\n\n\x06\x43ONFIG\x10\x03')
)



_MESSAGE_MESSAGETYPE = _descriptor.EnumDescriptor(
  name='MessageType',
  full_name='message.Message.MessageType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GETVALUE', index=0, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LEARN', index=1, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONFIG', index=2, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=458,
  serialized_end=508,
)
_sym_db.RegisterEnumDescriptor(_MESSAGE_MESSAGETYPE)


_MESSAGE_STATE = _descriptor.Descriptor(
  name='State',
  full_name='message.Message.State',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ballVelX', full_name='message.Message.State.ballVelX', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ballVelY', full_name='message.Message.State.ballVelY', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='playerVelX', full_name='message.Message.State.playerVelX', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='playerVelY', full_name='message.Message.State.playerVelY', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='distance', full_name='message.Message.State.distance', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='angleToBall', full_name='message.Message.State.angleToBall', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=170,
  serialized_end=292,
)

_MESSAGE_CONFIG = _descriptor.Descriptor(
  name='Config',
  full_name='message.Message.Config',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='isTraining', full_name='message.Message.Config.isTraining', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=294,
  serialized_end=322,
)

_MESSAGE_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='message.Message.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='message.Message.Request.state', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='target', full_name='message.Message.Request.target', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='config', full_name='message.Message.Request.config', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=324,
  serialized_end=429,
)

_MESSAGE_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='message.Message.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='message.Message.Response.value', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=431,
  serialized_end=456,
)

_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='message.Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='message.Message.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='request', full_name='message.Message.request', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='response', full_name='message.Message.response', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_MESSAGE_STATE, _MESSAGE_CONFIG, _MESSAGE_REQUEST, _MESSAGE_RESPONSE, ],
  enum_types=[
    _MESSAGE_MESSAGETYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=508,
)

_MESSAGE_STATE.containing_type = _MESSAGE
_MESSAGE_CONFIG.containing_type = _MESSAGE
_MESSAGE_REQUEST.fields_by_name['state'].message_type = _MESSAGE_STATE
_MESSAGE_REQUEST.fields_by_name['config'].message_type = _MESSAGE_CONFIG
_MESSAGE_REQUEST.containing_type = _MESSAGE
_MESSAGE_RESPONSE.containing_type = _MESSAGE
_MESSAGE.fields_by_name['type'].enum_type = _MESSAGE_MESSAGETYPE
_MESSAGE.fields_by_name['request'].message_type = _MESSAGE_REQUEST
_MESSAGE.fields_by_name['response'].message_type = _MESSAGE_RESPONSE
_MESSAGE_MESSAGETYPE.containing_type = _MESSAGE
DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), dict(

  State = _reflection.GeneratedProtocolMessageType('State', (_message.Message,), dict(
    DESCRIPTOR = _MESSAGE_STATE,
    __module__ = 'message_pb2'
    # @@protoc_insertion_point(class_scope:message.Message.State)
    ))
  ,

  Config = _reflection.GeneratedProtocolMessageType('Config', (_message.Message,), dict(
    DESCRIPTOR = _MESSAGE_CONFIG,
    __module__ = 'message_pb2'
    # @@protoc_insertion_point(class_scope:message.Message.Config)
    ))
  ,

  Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
    DESCRIPTOR = _MESSAGE_REQUEST,
    __module__ = 'message_pb2'
    # @@protoc_insertion_point(class_scope:message.Message.Request)
    ))
  ,

  Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
    DESCRIPTOR = _MESSAGE_RESPONSE,
    __module__ = 'message_pb2'
    # @@protoc_insertion_point(class_scope:message.Message.Response)
    ))
  ,
  DESCRIPTOR = _MESSAGE,
  __module__ = 'message_pb2'
  # @@protoc_insertion_point(class_scope:message.Message)
  ))
_sym_db.RegisterMessage(Message)
_sym_db.RegisterMessage(Message.State)
_sym_db.RegisterMessage(Message.Config)
_sym_db.RegisterMessage(Message.Request)
_sym_db.RegisterMessage(Message.Response)


# @@protoc_insertion_point(module_scope)
